import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
export const metadata: Metadata = {
  title: "Cognitry",
  description: "Generated by Cognitry",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="canonical" href="https://www.cognitry.io/" />
      </Head>
      <body
      >
        {children}
      </body>
    </html>
  );
}
