import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Cognitry",
  description: "Generated by Cognitry",
  alternates: {
    canonical: "https://www.cognitry.io/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
